### ISSUE TITLE
Python error when exporting scene with HG human from Blender.

### ISSUE THREAD

**Issue by radman-x** [OliverJPost/HumGen3D#36]
**Describe the bug**
Python error when exporting scene with HG human from Blender.

**To Reproduce**
1. Open Blender 3.3.1
2. Click New File | General
3. Open Add-on pane (eg, via N key).
4. Click on HumGen (vertical) tab.
5. Click human browser, with Male selected, and choose Asian1.
6. Click Generate New Human. Wait until done...
7. Click File | Export | GLTF 2.0 (gltf/glb)
8. Navigate to desired output folder
9. Click Export gLTF 2.0.
10. Cursor becomes black square.
11. See error pop-up. Here is the error stack in the system console:

20:29:11 | INFO: Starting glTF 2.0 export
20:29:12 | INFO: Extracting primitive: Female_Body_Default
20:29:14 | INFO: Primitives created: 1
20:29:14 | WARNING: There are more than 4 joint vertex influences.The 4 with highest weight will be used (and normalized).
H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_texture_specular.py:76: RuntimeWarning: invalid value encountered in true_divide
  return c / stack3(l)
Traceback (most recent call last):
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 69, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 31, in gather_node
    children=__gather_children(vnode, blender_object, export_settings),
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 73, in __gather_children
    node = gather_node(c, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 35, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 246, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 61, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 147, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 83, in gather_primitives
    material = gltf2_blender_gather_materials.gather_material(
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 57, in gather_material
    extensions, uvmap_actives_extensions = __gather_extensions(blender_material, emissive_factor, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials.py", line 250, in __gather_extensions
    specular_extension, use_actives_uvmap_specular = export_specular(blender_material, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_materials_specular.py", line 149, in export_specular
    specularColorTexture, use_active_uvmap, specularColorFactor = gltf2_blender_gather_texture_info.gather_texture_info(
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 23, in gather_texture_info
    return __gather_texture_info_helper(primary_socket, blender_shader_sockets, 'DEFAULT', filter_type, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 44, in __gather_texture_info_helper
    index, factor = __gather_index(blender_shader_sockets, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture_info.py", line 141, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture.py", line 31, in gather_texture
    source, factor = __gather_source(blender_shader_sockets, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_texture.py", line 83, in __gather_source
    return gltf2_blender_gather_image.gather_image(blender_shader_sockets, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_image.py", line 46, in gather_image
    buffer_view, factor_buffer_view = __gather_buffer_view(image_data, mime_type, name, export_settings)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_image.py", line 106, in __gather_buffer_view
    data, factor = image_data.encode(mime_type)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_image.py", line 142, in encode
    pixels, width, height, factor = self.numpy_calc(self.stored)
  File "H:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_texture_specular.py", line 81, in specular_calculation
    out_buf = (1 - stack3(buffers['transmission'])) * (1 / f0_from_ior) * 0.08 * stack3(buffers['specular']) * tint_strength + stack3(buffers['transmission']) * tint_strength
ZeroDivisionError: float division by zero

**Desktop:**
 - OS: Windows 10
 - Blender Version 3.3.1
 - Human Generator Version 4.01 (also happens in v3)

**Comment by OliverJPost** [comment]
Thanks for reporting! It's caused by this bug in Blender https://developer.blender.org/T102272
They say it should be fixed for the next Blender 3.3.2
I don't think there is something we can do from our side to circumvent the error.

**Comment by radman-x** [comment]
Closing this as it is fixed with the latest Blender release (v3.4). However, several other HG -> GLTF bugs (will report in separate issues).

**Comment by radman-x** [comment]
I am re-opening this since it still occurs in Blender v3.3.2, contrary to what you said above. It seems to be fixed in v3.3.4 but there are many bugs in HG running in v3.3.4 so I'm leaving this open until we get a working version of HG in a released version (now 3.3.2) of Blender (ideally, a fully released version of HG but at least a beta).

**Comment by radman-x** [comment]
This still occurs in HG v4.beta.6.

**Comment by radman-x** [comment]
Any updates on this? Seem the fix from Blender https://developer.blender.org/T102272 is in Blender v3.4 but this bug still exists.

**Comment by radman-x** [comment]
As a hack, adding the following code before line 82 in Blender/3.4\3.4\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_texture_specular.py solves this problem (though not sure specularity is exported correctly:

    if f0_from_ior == 0:
        f0_from_ior = 1e-10

Not a good solution but at least GLTF exporting "works" (still has lots of problems but doesn't crash).

**Comment by OliverJPost** [comment]
I have been exploring this further, and adding the line you suggest does indeed fix the issue. I am considering making HG overwrite the `gltf2_blender_texture_specular.py` file on the Blender versions that are affected.

**Comment by OliverJPost** [comment]
This issue has been fixed in [#8717db2484583486ab78b0ecca378e2543a9ee70](https://github.com/OliverJPost/HumGen3D/commit/8717db2484583486ab78b0ecca378e2543a9ee70). Will be included in next release, but the latest main should be stable to use too.

In the end the 0 value could be prevented by either ensuring all materials (that use textures) are valid PBR materials or disconnecting the material in the case it is not.

**Comment by ygorlf** [comment]
Hi @OliverJPost, how can I install this version correctly on my blender? I downloaded the .zip file from the main branch e installed and when I click the checkbox to activate I got this error:

<img width="659" alt="Screen Shot 2023-03-28 at 17 19 38" src="https://user-images.githubusercontent.com/7098222/228357832-c36a831b-e8e7-49a6-8108-b798aceaae85.png">

**Comment by OliverJPost** [comment]
@ygorlf  This means you've downloaded the add-on zip directly from main, and it was likely named HumGen3D-main or something like that. This means it's been installed with that name. You can either rename the zip before installing or go into the Blender add-ons folder and rename the HumGen3D-main folder to just HumGen3D.
